plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.gradle
}

android {
    namespace = "net.svaroh.passly.core.sync"
}

dependencies {
    implementation platform(libs.koin.bom)
    implementation libs.koin
    implementation libs.work.runtime
}

kotlin {
    jvmToolchain(17)
}
